<?php

namespace client\controllers;

use Yii;
use common\controllers\CommonController;
use common\models\db\UserRole;
use yii\helpers\Url;
use yii\web\ForbiddenHttpException;
use common\helpers\UserHelpers;

class Controller extends CommonController
{
    public function beforeAction($action)
    {
//        if(Yii::$app->controller->action->id != 'error'){
//            if(!Yii::$app->user->isGuest){
//                if((UserRole::findOne(Yii::$app->user->identity->role_id)->name == 'admin'))
//                {
//                    throw new ForbiddenHttpException('You are not allowed to access this page.');
//                }
//            }else{
//                return UserHelpers::redirectToLoggedInUsersMod();
//            }
//        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}