<?php
namespace common\controllers;

use Yii;


class CommonController extends Controller
{


    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}